Checkpoint 1
falseness/diplomacy_cpp pull request #1
Opened 2021-03-23 23:52 UTC by falseness

Игру переписываю на с++ с хорошей архитектурой со своего же проекта https://falseness.github.io/diplomacy/.
Добавлено много классов на будущее, сделана отрисовка поля.
В файле architecture.svg основные классы всего проекта. На данный момент далеко не все классы есть. Более того, могут быть временные расхождения с архитектурой в реализации.

2021-04-04 13:35 UTC, Mrkol requested changes
Где часть архитектуры про Entity, Unit, Building? К первому чекпоинту именно это в первую очередь требовалось. Ну и new/delete полностью выпиливай. Заменяй на unique_ptr или даже хранение по значению, если не нужен полиморфизм.

2021-04-04 13:35 UTC, Mrkol commented on CMakeLists.txt
> +        source/options/options.cpp source/sprites/cell/cell.cpp source/sprites/cell/cell.h source/sprites/cell/coord_translation.cpp source/sprites/cell/coord_translation.h source/geometry/point.h)
Хедеры не нужно добавлять в список сурсов.

2021-04-04 13:35 UTC, Mrkol commented on source/game.cpp
> +    game_scene_ = new GameScene(game_options_);
New/delete запрещены. unique_ptr юзай

2021-04-04 13:35 UTC, Mrkol commented on source/game.h
> +#define DIPLOMACY_CPP_GAME_H
А можно просто pragma once

2021-04-04 13:35 UTC, Mrkol commented on source/sfml_facades/screen.h
> +    */
Не вижу фасада. У тебя жёстко привязан весь проект к sfml. Повсюду инклюды и классы из него. Где фасад-то?

2021-04-04 13:35 UTC, Mrkol commented on source/sprites/cell/hexagon.h
> +    sf::CircleShape* hexagon_;
Ну тут-то зачем по указателю хранить? Просто по значению храни и всё будет хорошо.

2021-04-04 13:35 UTC, Mrkol commented on source/sprites_groups/scene.h
> +class Scene : public SpritesGroup {
Почему сцена "является" группой спрайтов? Это не логично. Логично было бы если бы в сцене "содержалась" группа спрайтов. Какое-то сомнительно решение делать это через наследование.

2021-04-04 13:35 UTC, Mrkol commented on source/sprites_groups/sprites_group.h
> +class SpritesGroup : public Sprite {
А группа спрайтов в свою очередь является спрайтом. Что-то странное получается, очень нелогично.

2021-05-14 21:47 UTC, falseness commented
Выполнены старые требования выше и добавлены юниты.

2021-08-29 14:12 UTC, merged